modLoader = "javafml"
loaderVersion = "*"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Polynametag"
authors = "Polyfrost"
description = ""
logoFile = "assets/${mod_id}/polynametag.svg"

[["dependencies.${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[["dependencies.${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mixins.${mod_id}.json"
